### ISSUE TITLE
How to set kernelsize correctly? 

### ISSUE THREAD

**Issue by brianchou** [bendurston/robotframework-ocrlibrary#8]
How to set kernelsize correctly? 

I tried to set kernelsize to (1, 1) and (1, 1, 1) both got error message like below. 

InvalidKernelSize: The kernel size argument provided is invalid. Please provide a size that is a positive odd number of type tuple.

**Comment by bendurston** [comment]
Can you share your robot code?

**Comment by bendurston** [comment]
After using this keyword in a robot test, I realize that there is a bug affects all keywords that involve kernel sizes set as tuples. Thank you for bringing this to my attention @brianchou, I will fix this as soon as possible.

**Comment by bendurston** [comment]
This bug has been fixed in version 1.2.0
