### ISSUE TITLE
How to get the text from an image file?

### ISSUE THREAD

**Issue by brianchou** [bendurston/robotframework-ocrlibrary#9]
I can use the following code to get the text from image file, but I have no clue how to do this with the robotframework-ocrlibrary.

import pytesseract

custom_oem_psm_config = r'--oem 3 --psm 10'

code1 = pytesseract.image_to_string("Captcha.png", config=custom_oem_psm_config)

print(code1)

**Comment by bendurston** [comment]
I have not made a keyword to get the text from an image. But there is a keyword that validates the text in an image. 

To validate the text from an image in robotframework-ocrlibrary you can use the keyword `Validate Image Content` along with any image processing keyword.

Here is an example of its usage, assume that the image is not processed (i.e. a .png, .jpg, .jpeg file):

```
Keyword That Checks Image For Text
     [Arguments]      ${expected_text}     ${image}
     ${processed_image}     Get Binary Image     ${image}     ${TRUE}
     Validate Image Content     ${processed_image}     ${expected_text}
```

This weekend I will add a keyword that will get the text from an image.

**Comment by brianchou** [comment]
- "This weekend I will add a keyword that will get the text from an image."

That will be awesome.

**Comment by bendurston** [comment]
Keyword to get the text from an image has been added. See keyword `Get Image Content`.
